### ISSUE TITLE
로그인시 최근 로그인 날짜 및 회원가입시 축하금 지급로직

### ISSUE THREAD

**Issue by minseo9974** [nhnacademy-be4-InkBridge/backend#194]
로그인하면 최근 로그인 날짜를 오늘로 수정합니다.
회원가입시 축하금 정책에서 금액을 가져와 회원에게 포인트 축하금 내역을 기록하고 지급합니다.
회원 상태가 휴먼일때 로그인시 활동상태로 변경합니다.
회원 상태가 탈퇴라면 로그인 하지 못하게 변경했습니다.

**Comment by Huni0819** [comment]
고생하셨네요 멋지네요
