### ISSUE TITLE
리뷰 작성

### ISSUE THREAD

**Issue by Huni0819** [nhnacademy-be4-InkBridge/backend#220]
### Image1

![Image](https://github.com/nhnacademy-be4-InkBridge/frontend/assets/122001936/0fd1b7b7-dfae-4c3e-ba98-15c7c40e5baf)

### Image2

![Image](https://github.com/nhnacademy-be4-InkBridge/frontend/assets/122001936/629be984-b9b2-4f7c-8616-5c2fdf2a6768)

### 발견시간
2024년 03월 34일 (금) 오후 08시 34분

### 발견 오류
마이페이지에서 리뷰 작성 시 리뷰 등록이 되지 않습니다.

**Comment by minm063** [comment]
수정했습니다 #221
